=== wybieralski/TB2/projecto1/bills/templates/bakery_sales.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="CompanySales" type="CompanySalesType"/>
  <xs:complexType name="ClientType">
    <xs:sequence>
      <xs:element name="ClientID">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="01"/>
            <xs:enumeration value="02"/>
            <xs:enumeration value="03"/>
            <xs:enumeration value="04"/>
            <xs:enumeration value="05"/>
            <xs:enumeration value="06"/>
            <xs:enumeration value="07"/>
            <xs:enumeration value="08"/>
            <xs:enumeration value="09"/>
            <xs:enumeration value="10"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ClientName">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Agrupamento de Escolas de Ovar"/>
            <xs:enumeration value="Agrupamento de Escolas Ovar Sul"/>
            <xs:enumeration value="Confeitaria Convívio 2 Paiva e Correia L.da"/>
            <xs:enumeration value="Restaurante Paradise"/>
            <xs:enumeration value=" Junta Freguesia de Válega "/>
            <xs:enumeration value="Estabelecimentos Alentejano António Álvaro da Silva Matos"/>
            <xs:enumeration value=" Centro Cultural e Recrea. de Válega "/>
            <xs:enumeration value=" I.V.S. Irmaos Vaz e Silva e C  Lda "/>
            <xs:enumeration value="Casa Alentejana - Ovar Rijo Freire e Silva"/>
            <xs:enumeration value="A.D.O. Basquetebol"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="ClientAddressType" name="ClientAddress"/>
      <xs:element type="ClientContactType" name="ClientContact"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TransactionType">
    <xs:sequence>
      <xs:element name="TransactionID">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value=" 01 "/>
            <xs:enumeration value=" 02 "/>
            <xs:enumeration value=" 03 "/>
            <xs:enumeration value=" 04 "/>
            <xs:enumeration value=" 05 "/>
            <xs:enumeration value=" 06 "/>
            <xs:enumeration value=" 07 "/>
            <xs:enumeration value=" 08 "/>
            <xs:enumeration value=" 09 "/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ClientID">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value=" 01 "/>
            <xs:enumeration value=" 02 "/>
            <xs:enumeration value=" 03 "/>
            <xs:enumeration value=" 04 "/>
            <xs:enumeration value=" 05 "/>
            <xs:enumeration value=" 06 "/>
            <xs:enumeration value=" 07 "/>
            <xs:enumeration value=" 08 "/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ClientName">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Agrupamento de Escolas de Ovar"/>
            <xs:enumeration value="Agrupamento de Escolas Ovar Sul"/>
            <xs:enumeration value="Confeitaria Convívio 2 Paiva e Correia L.da"/>
            <xs:enumeration value="Restaurante Paradise"/>
            <xs:enumeration value=" Junta Freguesia de Válega "/>
            <xs:enumeration value="Estabelecimentos Alentejano António Álvaro da Silva Matos"/>
            <xs:enumeration value=" Centro Cultural e Recrea. de Válega "/>
            <xs:enumeration value=" I.V.S. Irmaos Vaz e Silva e C  Lda "/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ProductID">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value=" 01 "/>
            <xs:enumeration value=" 02 "/>
            <xs:enumeration value=" 03 "/>
            <xs:enumeration value=" 04 "/>
            <xs:enumeration value=" 05 "/>
            <xs:enumeration value=" 06 "/>
            <xs:enumeration value=" 07 "/>
            <xs:enumeration value=" 08 "/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ProductName">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Pão"/>
            <xs:enumeration value="Pastéis"/>
            <xs:enumeration value="Croissant"/>
            <xs:enumeration value="Bicos de Pato"/>
            <xs:enumeration value="Broa de Milho"/>
            <xs:enumeration value="Bolo Rei"/>
            <xs:enumeration value="Regueifa"/>
            <xs:enumeration value="Pão de forma"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ProductQuantity">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value=" 10 "/>
            <xs:enumeration value=" 5 "/>
            <xs:enumeration value=" 25 "/>
            <xs:enumeration value=" 250 "/>
            <xs:enumeration value=" 3 "/>
            <xs:enumeration value=" 4 "/>
            <xs:enumeration value=" 20 "/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="TotalCost">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value=" 1.05 "/>
            <xs:enumeration value=" 2.00 "/>
            <xs:enumeration value=" 9.25 "/>
            <xs:enumeration value=" 92.50 "/>
            <xs:enumeration value=" 5.10 "/>
            <xs:enumeration value=" 35.20 "/>
            <xs:enumeration value=" 5.50 "/>
            <xs:enumeration value=" 6.00 "/>
            <xs:enumeration value=" 2.05 "/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="TransactionTimeType" name="TransactionTime"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ContactType">
    <xs:sequence>
      <xs:element type="xs:string" name="Telephone"/>
      <xs:element type="xs:string" name="Fax"/>
      <xs:element type="xs:string" name="Email"/>
      <xs:element type="xs:string" name="Website"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TransactionTimeType">
    <xs:sequence>
      <xs:element name="Date">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value=" 18/10/2017 "/>
            <xs:enumeration value=" 22/10/2017 "/>
            <xs:enumeration value=" 17/10/2017 "/>
            <xs:enumeration value=" 24/10/2017 "/>
            <xs:enumeration value=" 16/10/2017 "/>
            <xs:enumeration value=" 24/12/2017 "/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Time">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value=" 16:00 "/>
            <xs:enumeration value=" 17:32 "/>
            <xs:enumeration value=" 12:32 "/>
            <xs:enumeration value=" 17:19 "/>
            <xs:enumeration value=" 15:20 "/>
            <xs:enumeration value=" 12:20 "/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ProductType">
    <xs:sequence>
      <xs:element type="xs:string" name="ProductID"/>
      <xs:element type="xs:string" name="ProductName"/>
      <xs:element type="xs:string" name="UnitCost"/>
      <xs:element type="TaxType" name="Tax"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CompanyType">
    <xs:sequence>
      <xs:element type="xs:string" name="CompanyId"/>
      <xs:element type="xs:string" name="TaxRegistrationNumber"/>
      <xs:element type="xs:string" name="CompanyName"/>
      <xs:element type="xs:string" name="BusinessName"/>
      <xs:element type="xs:string" name="CurrencyCode"/>
      <xs:element type="AddressType" name="Address"/>
      <xs:element type="ContactType" name="Contact"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ClientContactType">
    <xs:sequence>
      <xs:element name="Telephone">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="256581000"/>
            <xs:enumeration value="256502347"/>
            <xs:enumeration value=" "/>
            <xs:enumeration value="256575661"/>
            <xs:enumeration value="256502090"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Fax">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="256586411"/>
            <xs:enumeration value="256503246"/>
            <xs:enumeration value=" "/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Email">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="esjmf@portugalmail.pt"/>
            <xs:enumeration value=" "/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CompanyProductsType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="ProductType" name="Product"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="TaxType">
    <xs:sequence>
      <xs:element type="xs:string" name="TaxType"/>
      <xs:element name="Description">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Taxa Reduzida"/>
            <xs:enumeration value="Taxa Normal"/>
            <xs:enumeration value="Taxa Intermedia"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="TaxPercentage">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="6"/>
            <xs:enumeration value="23"/>
            <xs:enumeration value="13"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CompanyClientsType">
    <xs:sequence>
      <xs:element type="ClientType" name="Client" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ClientsTransactionsType">
    <xs:sequence>
      <xs:element type="TransactionType" name="Transaction" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ClientAddressType">
    <xs:sequence>
      <xs:element name="AddressDetail">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="R. Dom Dinis"/>
            <xs:enumeration value="R. Irmãos Oliveira Lopes"/>
            <xs:enumeration value="Rua das Palreiras - Válega"/>
            <xs:enumeration value="Rua Alexandre Herculano"/>
            <xs:enumeration value="Av. Comendador António Augusto da Silva"/>
            <xs:enumeration value="Rua das Estradas nº 678"/>
            <xs:enumeration value="Rua do Centro Cultural e Recreativo de Válega"/>
            <xs:enumeration value="Rua da Ponte Pedra Válega"/>
            <xs:enumeration value="Ovar"/>
            <xs:enumeration value=" Ovar "/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="City">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Ovar"/>
            <xs:enumeration value="Válega"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PostalCode">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="3880-000"/>
            <xs:enumeration value="3880-192"/>
            <xs:enumeration value="3880-508"/>
            <xs:enumeration value="3880-503"/>
            <xs:enumeration value="3880-549"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="Region"/>
      <xs:element type="xs:string" name="Country"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="AddressType">
    <xs:sequence>
      <xs:element type="xs:string" name="BuildingNumber"/>
      <xs:element type="xs:string" name="StreetName"/>
      <xs:element type="xs:string" name="AddressDetail"/>
      <xs:element type="xs:string" name="City"/>
      <xs:element type="xs:string" name="PostalCode"/>
      <xs:element type="xs:string" name="Region"/>
      <xs:element type="xs:string" name="Country"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CompanySalesType">
    <xs:sequence>
      <xs:element type="CompanyType" name="Company"/>
      <xs:element type="CompanyProductsType" name="CompanyProducts"/>
      <xs:element type="CompanyClientsType" name="CompanyClients"/>
      <xs:element type="ClientsTransactionsType" name="ClientsTransactions"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== wybieralski/TB2/projecto1/bills/templates/bakery_sales.xml
<?xml version="1.0"?>
<!--
Sites visited:
https://msdn.microsoft.com/en-us/library/ms757863(v=vs.85).aspx
Slides visited:
edc.02d.pdf
-->
<CompanySales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bakery_sales.xsd">
	<Company>
		<CompanyId> 513581332 </CompanyId>
		<TaxRegistrationNumber> 513581332 </TaxRegistrationNumber>
		<CompanyName> PADARIA PASTELARIA SARGACAL LDA.  </CompanyName>
		<BusinessName> PADARIA PASTELARIA SARGACAL LDA. </BusinessName>
		<CurrencyCode>EUR</CurrencyCode>
		<Address>
			<BuildingNumber> </BuildingNumber>
			<StreetName> </StreetName>
			<AddressDetail>RUA 15 DE MAIO, 735</AddressDetail>
			<City>Válega</City>
			<PostalCode>3880-503</PostalCode>
			<Region> </Region>
			<Country>PT</Country>
		</Address>
		<Contact>
			<Telephone> </Telephone>
			<Fax> </Fax>
			<Email> </Email>
			<Website> </Website>
		</Contact>
	</Company>

	<CompanyProducts>
		<Product>
			<ProductID>01</ProductID>
			<ProductName>Pão</ProductName>
			<UnitCost>0.105</UnitCost>
            <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Reduzida</Description>
                <TaxPercentage>6</TaxPercentage>
            </Tax>
		</Product>

		<Product>
			<ProductID>02</ProductID>
			<ProductName>Pastéis</ProductName>
			<UnitCost>0.40</UnitCost>
           <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Normal</Description>
                <TaxPercentage>23</TaxPercentage>
            </Tax>
		</Product>

		<Product>
			<ProductID>03</ProductID>
			<ProductName>Croissant</ProductName>
			<UnitCost>0.37</UnitCost>
            <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Reduzida</Description>
                <TaxPercentage>6</TaxPercentage>
            </Tax>
		</Product>

		<Product>
			<ProductID>04</ProductID>
			<ProductName>Bicos de Pato</ProductName>
			<UnitCost>0.37</UnitCost>
            <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Reduzida</Description>
                <TaxPercentage>6</TaxPercentage>
            </Tax>
		</Product>

		<Product>
			<ProductID>05</ProductID>
			<ProductName>Broa de Milho</ProductName>
			<UnitCost>1.70</UnitCost>
            <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Reduzida</Description>
                <TaxPercentage>6</TaxPercentage>
            </Tax>
		</Product>

		<Product>
			<ProductID>06</ProductID>
			<ProductName>Bolo Rei</ProductName>
			<UnitCost>8.80</UnitCost>
            <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Normal</Description>
                <TaxPercentage>23</TaxPercentage>
            </Tax>
		</Product>

		<Product>
			<ProductID>07</ProductID>
			<ProductName>Regueifa</ProductName>
			<UnitCost>1.10</UnitCost>
            <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Reduzida</Description>
                <TaxPercentage>6</TaxPercentage>
            </Tax>
		</Product>

		<Product>
			<ProductID>08</ProductID>
			<ProductName>Pão de forma</ProductName>
			<UnitCost>1.50</UnitCost>
            <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Reduzida</Description>
                <TaxPercentage>6</TaxPercentage>
            </Tax>
		</Product>

		<Product>
			<ProductID>09</ProductID>
			<ProductName>Pão de ló de Ovar</ProductName>
			<UnitCost>10.00</UnitCost>
            <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Normal</Description>
                <TaxPercentage>23</TaxPercentage>
            </Tax>
		</Product>

		<Product>
			<ProductID>10</ProductID>
			<ProductName> Sandes queijo fiambre </ProductName>
			<UnitCost>0.75</UnitCost>
            <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Normal</Description>
                <TaxPercentage>23</TaxPercentage>
            </Tax>
		</Product>

		<Product>
			<ProductID>11</ProductID>
			<ProductName> Água mineral sem gás </ProductName>
			<UnitCost>0.40</UnitCost>
            <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Reduzida</Description>
                <TaxPercentage>6</TaxPercentage>
            </Tax>
		</Product>

        <Product>
			<ProductID>12</ProductID>
			<ProductName> Bolo de aniversário </ProductName>
			<UnitCost>9.50</UnitCost>
            <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Normal</Description>
                <TaxPercentage>23</TaxPercentage>
            </Tax>
		</Product>

        <Product>
			<ProductID>13</ProductID>
			<ProductName> Pão da avó </ProductName>
			<UnitCost>1.65</UnitCost>
            <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Reduzida</Description>
                <TaxPercentage>6</TaxPercentage>
            </Tax>
		</Product>

        <Product>
			<ProductID>14</ProductID>
			<ProductName> Pão de mistura </ProductName>
			<UnitCost>0.105</UnitCost>
            <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Reduzida</Description>
                <TaxPercentage>6</TaxPercentage>
            </Tax>
		</Product>

        <Product>
			<ProductID>15</ProductID>
			<ProductName> Pão integral </ProductName>
			<UnitCost>0.105</UnitCost>
            <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Reduzida</Description>
                <TaxPercentage>6</TaxPercentage>
            </Tax>
		</Product>

        <Product>
			<ProductID>16</ProductID>
			<ProductName> Fogaças </ProductName>
			<UnitCost>3.50</UnitCost>
            <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Intermedia</Description>
                <TaxPercentage>13</TaxPercentage>
            </Tax>
		</Product>

        <Product>
			<ProductID>17</ProductID>
			<ProductName> Folares </ProductName>
			<UnitCost>6.00</UnitCost>
            <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Intermedia</Description>
                <TaxPercentage>13</TaxPercentage>
            </Tax>
		</Product>

        <Product>
			<ProductID>18</ProductID>
			<ProductName> Miniaturas de pasteis </ProductName>
			<UnitCost>0.35</UnitCost>
            <Tax>
                <TaxType>IVA</TaxType>
                <Description>Taxa Normal</Description>
                <TaxPercentage>23</TaxPercentage>
            </Tax>
		</Product>

	</CompanyProducts>

	<CompanyClients>
		<Client>
			<ClientID>01</ClientID>
			<ClientName>Agrupamento de Escolas de Ovar</ClientName>
			<ClientAddress>
				<AddressDetail>R. Dom Dinis</AddressDetail>
				<City>Ovar</City>
				<PostalCode>3880-000</PostalCode>
				<Region> </Region>
				<Country>PT</Country>
			</ClientAddress>
			<ClientContact>
				<Telephone>256581000</Telephone>
				<Fax>256586411</Fax>
				<Email>esjmf@portugalmail.pt</Email>
			</ClientContact>
		</Client>

		<Client>
			<ClientID>02</ClientID>
			<ClientName>Agrupamento de Escolas Ovar Sul</ClientName>
			<ClientAddress>
				<AddressDetail>R. Irmãos Oliveira Lopes</AddressDetail>
				<City>Ovar</City>
				<PostalCode>3880-192</PostalCode>
				<Region> </Region>
				<Country>PT</Country>
			</ClientAddress>
			<ClientContact>
				<Telephone>256502347</Telephone>
				<Fax>256503246</Fax>
				<Email> </Email>
			</ClientContact>
		</Client>

		<Client>
			<ClientID>03</ClientID>
			<ClientName>Confeitaria Convívio 2 Paiva e Correia L.da</ClientName>
			<ClientAddress>
				<AddressDetail>Rua das Palreiras - Válega</AddressDetail>
				<City>Ovar</City>
				<PostalCode>3880-000</PostalCode>
				<Region> </Region>
				<Country>PT</Country>
			</ClientAddress>
			<ClientContact>
				<Telephone> </Telephone>
				<Fax> </Fax>
				<Email> </Email>
			</ClientContact>
		</Client>

		<Client>
			<ClientID>04</ClientID>
			<ClientName>Restaurante Paradise</ClientName>
			<ClientAddress>
				<AddressDetail>Rua Alexandre Herculano</AddressDetail>
				<City>Ovar</City>
				<PostalCode>3880-000</PostalCode>
				<Region> </Region>
				<Country>PT</Country>
			</ClientAddress>
			<ClientContact>
				<Telephone>256575661</Telephone>
				<Fax> </Fax>
				<Email> </Email>
			</ClientContact>
		</Client>

		<Client>
			<ClientID>05</ClientID>
			<ClientName> Junta Freguesia de Válega </ClientName>
			<ClientAddress>
				<AddressDetail>Av. Comendador António Augusto da Silva</AddressDetail>
				<City>Válega</City>
				<PostalCode>3880-000</PostalCode>
				<Region> </Region>
				<Country>PT</Country>
			</ClientAddress>
			<ClientContact>
				<Telephone>256575661</Telephone>
				<Fax> </Fax>
				<Email> </Email>
			</ClientContact>
		</Client>

		<Client>
			<ClientID>06</ClientID>
			<ClientName>Estabelecimentos Alentejano António Álvaro da Silva Matos</ClientName>
			<ClientAddress>
				<AddressDetail>Rua das Estradas nº 678</AddressDetail>
				<City>Válega</City>
				<PostalCode>3880-508</PostalCode>
				<Region> </Region>
				<Country>PT</Country>
			</ClientAddress>
			<ClientContact>
				<Telephone>256502090</Telephone>
				<Fax> </Fax>
				<Email> </Email>
			</ClientContact>
		</Client>

		<Client>
			<ClientID>07</ClientID>
			<ClientName> Centro Cultural e Recrea. de Válega </ClientName>
			<ClientAddress>
				<AddressDetail>Rua do Centro Cultural e Recreativo de Válega</AddressDetail>
				<City>Válega</City>
				<PostalCode>3880-503</PostalCode>
				<Region> </Region>
				<Country>PT</Country>
			</ClientAddress>
			<ClientContact>
				<Telephone> </Telephone>
